resize:
  width: 640
  height: 640

image_data_paths:
  images: data/raw/images
  info_csv_file: data/raw/image_info.csv
  bboxes_csv_file: data/raw/bboxes/bounding_boxes.csv
  train_csv_file: data/processed/train.csv
  test_csv_file: data/processed/test.csv
